version: '3.1'


services:

  reflector:
    image: 'node:6'
    privileged: true
    restart: always
    working_dir: /usr/src
    command: [ 'node', 'index.js' ]
    # command: [ 'node', '--debug-brk=5860', 'index.js' ]
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - '8000:8000/tcp'
    volumes:
      - ./src:/usr/src
      - ./node_modules:/usr/src/node_modules
      
